// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosminer/miner_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MinerInfo struct {
	TemplateNextID uint64 `protobuf:"varint,1,opt,name=templateNextID,proto3" json:"templateNextID,omitempty"`
	MinerNextID    uint64 `protobuf:"varint,2,opt,name=minerNextID,proto3" json:"minerNextID,omitempty"`
}

func (m *MinerInfo) Reset()         { *m = MinerInfo{} }
func (m *MinerInfo) String() string { return proto.CompactTextString(m) }
func (*MinerInfo) ProtoMessage()    {}
func (*MinerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cecca70acca2a7b2, []int{0}
}
func (m *MinerInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MinerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MinerInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MinerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerInfo.Merge(m, src)
}
func (m *MinerInfo) XXX_Size() int {
	return m.Size()
}
func (m *MinerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MinerInfo proto.InternalMessageInfo

func (m *MinerInfo) GetTemplateNextID() uint64 {
	if m != nil {
		return m.TemplateNextID
	}
	return 0
}

func (m *MinerInfo) GetMinerNextID() uint64 {
	if m != nil {
		return m.MinerNextID
	}
	return 0
}

func init() {
	proto.RegisterType((*MinerInfo)(nil), "luktechlabs.cosmosminer.cosmosminer.MinerInfo")
}

func init() { proto.RegisterFile("cosmosminer/miner_info.proto", fileDescriptor_cecca70acca2a7b2) }

var fileDescriptor_cecca70acca2a7b2 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xce, 0xcd, 0xcc, 0x4b, 0x2d, 0xd2, 0x07, 0x93, 0xf1, 0x99, 0x79, 0x69, 0xf9, 0x7a,
	0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xca, 0x39, 0xa5, 0xd9, 0x25, 0xa9, 0xc9, 0x19, 0x39, 0x89,
	0x49, 0xc5, 0x7a, 0x48, 0x2a, 0x91, 0xd9, 0x4a, 0xa1, 0x5c, 0x9c, 0xbe, 0x20, 0x86, 0x67, 0x5e,
	0x5a, 0xbe, 0x90, 0x1a, 0x17, 0x5f, 0x49, 0x6a, 0x6e, 0x41, 0x4e, 0x62, 0x49, 0xaa, 0x5f, 0x6a,
	0x45, 0x89, 0xa7, 0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x9a, 0xa8, 0x90, 0x02, 0x17,
	0x37, 0x58, 0x37, 0x54, 0x11, 0x13, 0x58, 0x11, 0xb2, 0x90, 0x53, 0xd0, 0x89, 0x47, 0x72, 0x8c,
	0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72,
	0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x59, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7,
	0xe7, 0xea, 0x43, 0x1d, 0xa8, 0x0b, 0x72, 0xa1, 0x3e, 0xc4, 0x55, 0xba, 0x10, 0xcf, 0x54, 0xe8,
	0x23, 0x7b, 0xad, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0xec, 0x2d, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0x4c, 0x98, 0x10, 0xf6, 0x00, 0x00, 0x00,
}

func (m *MinerInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MinerInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MinerInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinerNextID != 0 {
		i = encodeVarintMinerInfo(dAtA, i, uint64(m.MinerNextID))
		i--
		dAtA[i] = 0x10
	}
	if m.TemplateNextID != 0 {
		i = encodeVarintMinerInfo(dAtA, i, uint64(m.TemplateNextID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMinerInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovMinerInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MinerInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TemplateNextID != 0 {
		n += 1 + sovMinerInfo(uint64(m.TemplateNextID))
	}
	if m.MinerNextID != 0 {
		n += 1 + sovMinerInfo(uint64(m.MinerNextID))
	}
	return n
}

func sovMinerInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMinerInfo(x uint64) (n int) {
	return sovMinerInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MinerInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMinerInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MinerInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MinerInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TemplateNextID", wireType)
			}
			m.TemplateNextID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinerInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TemplateNextID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerNextID", wireType)
			}
			m.MinerNextID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinerInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinerNextID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMinerInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMinerInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMinerInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMinerInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMinerInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMinerInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMinerInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMinerInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMinerInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMinerInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMinerInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMinerInfo = fmt.Errorf("proto: unexpected end of group")
)
